# Generated by Django 5.2.1 on 2025-05-25 12:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0002_alter_manufacturer_website'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shelf',
            name='warehouse',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='shelves', to='inventory.warehouse'),
        ),
    ]
